/** Employee classification used by the Employees module. Each top-level
 *  bucket lists the specific job titles that fall under it; the Add /
 *  Edit Employee form renders a cascading dropdown driven by this map.
 *  Kept as a flat list so it's trivial to extend or translate later. */
export const EMPLOYEE_CATEGORIES: { category: string; roles: string[] }[] = [
  {
    category: "Leadership / Administration",
    roles: [
      "School Owner / Proprietor",
      "Superintendent",
      "Principal / Head of School",
      "Vice Principal / Assistant Principal",
      "Academic Director",
      "Administrative Director",
      "Operations Manager",
      "School Board Member",
      "Department Head",
      "Grade-Level Coordinator",
      "Program Coordinator",
    ],
  },
  {
    category: "Teaching / Academic Staff",
    roles: [
      "Classroom Teacher",
      "Subject Teacher",
      "Homeroom Teacher",
      "Substitute Teacher",
      "Teaching Assistant",
      "Teacher Aide",
      "Special Education Teacher",
      "ESL / Language Support Teacher",
      "Literacy Specialist",
      "Math Specialist",
      "Science Lab Teacher",
      "Physical Education Teacher",
      "Art Teacher",
      "Music Teacher",
      "Computer / ICT Teacher",
      "Religious Studies Teacher",
      "Librarian / Media Specialist",
    ],
  },
  {
    category: "Student Support Staff",
    roles: [
      "School Counselor",
      "Academic Advisor",
      "Career Counselor",
      "Social Worker",
      "Psychologist",
      "Behavior Specialist",
      "Student Support Coordinator",
      "Special Needs Coordinator",
      "Speech Therapist",
      "Occupational Therapist",
      "Nurse",
      "Attendance Officer",
      "Discipline Officer",
    ],
  },
  {
    category: "Office / Administrative Staff",
    roles: [
      "School Secretary",
      "Front Desk Receptionist",
      "Admissions Officer",
      "Registrar",
      "Records Officer",
      "Data Entry Clerk",
      "Exam Officer",
      "Parent Liaison Officer",
      "Communications Officer",
      "HR Officer",
      "Payroll Officer",
    ],
  },
  {
    category: "Finance / Business Office",
    roles: [
      "Accountant",
      "Bookkeeper",
      "Finance Manager",
      "Tuition / Fees Officer",
      "Billing Officer",
      "Procurement Officer",
      "Inventory Officer",
      "Cashier",
    ],
  },
  {
    category: "Technology / IT Staff",
    roles: [
      "IT Manager",
      "Systems Administrator",
      "Network Administrator",
      "Technical Support Officer",
      "Educational Technology Coordinator",
      "Website / App Administrator",
      "Data Manager",
    ],
  },
  {
    category: "Facilities / Maintenance",
    roles: [
      "Facilities Manager",
      "Maintenance Supervisor",
      "Electrician",
      "Plumber",
      "Carpenter",
      "Cleaner / Janitor",
      "Groundskeeper",
      "Security Guard",
      "School Safety Officer",
    ],
  },
  {
    category: "Transportation",
    roles: [
      "Transportation Manager",
      "Bus Driver",
      "Van Driver",
      "Bus Monitor",
      "Mechanic",
    ],
  },
  {
    category: "Food Services",
    roles: [
      "Cafeteria Manager",
      "Cook",
      "Kitchen Assistant",
      "Food Server",
      "Nutrition Coordinator",
    ],
  },
  {
    category: "Extracurricular / Student Activities",
    roles: [
      "Sports Coach",
      "Club Advisor",
      "Debate Coach",
      "Drama Coach",
      "After-School Program Coordinator",
      "Field Trip Coordinator",
    ],
  },
  {
    category: "Boarding School Staff",
    roles: [
      "Dormitory Supervisor",
      "House Parent",
      "Residential Life Coordinator",
      "Boarding Nurse",
      "Night Supervisor",
      "Laundry Staff",
    ],
  },
  {
    category: "College / University Setting",
    roles: [
      "Dean",
      "Professor",
      "Lecturer",
      "Academic Advisor",
      "Department Chair",
      "Research Assistant",
      "Lab Technician",
      "Financial Aid Officer",
      "Student Affairs Officer",
      "Career Services Officer",
      "Campus Security",
      "Admissions Counselor",
    ],
  },
];

export const rolesForCategory = (category: string): string[] =>
  EMPLOYEE_CATEGORIES.find((c) => c.category === category)?.roles ?? [];
