"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { UserRole } from "@/types";

interface UserContext {
  profileId: string;
  userId: string;
  schoolId: string;
  schoolName: string;
  schoolType: "public" | "private";
  role: UserRole;
  firstName: string;
  lastName: string;
  email: string;
  avatarUrl: string | null;
  /** Legacy school-issued ID from migration 028 (`[PREFIX][6-digit]`).
   *  Kept on the context only for the backwards-compat window — UI
   *  should display `institutionalId` instead. */
  memberId: string | null;
  /** Per-school per-role ID (`[PREFIX][ROLE_LETTER][6-digit]`).
   *  Generated by the DB trigger in migration 029. Null for parents
   *  and the platform admin. */
  institutionalId: string | null;
}

interface AuthContextType {
  user: UserContext | null;
  loading: boolean;
  signIn: (email: string, password: string) => Promise<{ error?: string; role?: UserRole }>;
  signOut: () => Promise<void>;
}

const AuthContext = createContext<AuthContextType>({
  user: null,
  loading: true,
  signIn: async () => ({}),
  signOut: async () => {},
});

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<UserContext | null>(null);
  const [loading, setLoading] = useState(true);
  const supabase = createClient();
  const router = useRouter();

  const fetchUserContext = async () => {
    try {
      if (!supabase || !process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL.includes('your_supabase')) {
        setUser(null);
        setLoading(false);
        return;
      }

      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        setUser(null);
        return;
      }

      const { data, error } = await supabase.rpc("get_user_context");
      if (error || !data || data.error) {
        setUser(null);
        return;
      }

      setUser({
        profileId: data.profile_id,
        userId: data.user_id,
        schoolId: data.school_id,
        schoolName: data.school_name,
        schoolType: data.school_type,
        role: data.role,
        firstName: data.first_name,
        lastName: data.last_name,
        email: data.email,
        avatarUrl: data.avatar_url,
        memberId: data.member_id ?? null,
        institutionalId: data.institutional_id ?? null,
      });
    } catch {
      setUser(null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchUserContext();

    // If Supabase isn't configured, createClient() returns null. Guard against
    // it so the whole app doesn't crash (which would unmount every page and
    // make tabs/buttons unclickable).
    if (!supabase) {
      setLoading(false);
      return;
    }

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      if (session) {
        fetchUserContext();
      } else {
        setUser(null);
        setLoading(false);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const signIn = async (email: string, password: string) => {
    if (!supabase) return { error: "Authentication is not configured. Please contact your administrator." };
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) return { error: error.message };

    // Verify the account can actually open a session. A suspended school or an
    // inactive profile authenticates at the auth layer but has no app context,
    // so reject it here with a clear message instead of a broken half-session.
    const { data, error: ctxError } = await supabase.rpc("get_user_context");
    if (ctxError || !data || data.error) {
      await supabase.auth.signOut();
      setUser(null);
      setLoading(false);
      const reason =
        data?.error === "School access suspended"
          ? "Your school's access has been suspended. Please contact the platform administrator."
          : data?.error === "No active profile found"
          ? "Your account is not active. Please contact your school administrator."
          : data?.error || ctxError?.message || "Unable to sign in. Please contact your administrator.";
      return { error: reason };
    }

    await fetchUserContext();
    return { role: data.role as UserRole };
  };

  const signOut = async () => {
    if (supabase) await supabase.auth.signOut();
    setUser(null);
    setLoading(false);
    // Navigate to the sign-in page; the dashboard has no auth guard, so
    // without this the user would just sit on the same page after logout.
    router.replace("/sign-in");
  };

  return (
    <AuthContext.Provider value={{ user, loading, signIn, signOut }}>
      {children}
    </AuthContext.Provider>
  );
}

export const useAuth = () => useContext(AuthContext);
