-- ═══════════════════════════════════════════════════════════════════
-- 028 · Auto-generated member IDs (student / teacher / staff IDs)
-- ───────────────────────────────────────────────────────────────────
-- Every student, teacher, school_admin and employee gets a stable
-- per-school identifier at the moment their profile is created. The
-- format follows the convention requested by the platform owner:
--
--   • Prefix = the first letter of each word in the school's name
--     (e.g. "Lincoln Academy" → "LA"). Single-word schools get a
--     single-letter prefix (e.g. "Lincoln" → "L"). Accented letters
--     are transliterated so "Académie" → "A".
--   • Suffix = a left-padded 6-digit sequence number per school
--     (000001, 000002, …), shared across roles so a single school
--     never has two members with the same ID.
--
-- Parents and the platform_admin do NOT receive a member ID — those
-- aren't operational identifiers a school issues. The trigger leaves
-- their member_id column NULL.
-- ═══════════════════════════════════════════════════════════════════

-- ─── Column ──────────────────────────────────────────────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS member_id TEXT;

-- One ID per school-member pair. Indexed for lookups by code.
CREATE UNIQUE INDEX IF NOT EXISTS uq_profiles_member_id_per_school
  ON public.profiles(school_id, member_id)
  WHERE member_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_member_id
  ON public.profiles(member_id) WHERE member_id IS NOT NULL;

COMMENT ON COLUMN public.profiles.member_id IS
  'School-issued ID, e.g. "LA000123". Auto-generated by the
   set_profile_member_id trigger when the row is inserted with no
   explicit value. Format: prefix + 6 digits, where the prefix is the
   first letter of each word in the school name.';


-- ─── Helpers ─────────────────────────────────────────────────────

-- Compute the alphabetical prefix from a school name. Pure / immutable
-- so it can be used in defaults and indexes.
CREATE OR REPLACE FUNCTION public.compute_school_prefix(s_name TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  parts TEXT[];
  w     TEXT;
  c     TEXT;
  out   TEXT := '';
BEGIN
  -- Split on any whitespace. coalesce protects against NULL.
  parts := regexp_split_to_array(trim(coalesce(s_name, '')), '\s+');
  FOREACH w IN ARRAY parts LOOP
    IF length(w) = 0 THEN CONTINUE; END IF;
    -- Upper-case the first character, then transliterate the common
    -- accented forms back to ASCII. Anything still outside A-Z is
    -- dropped (numbers, punctuation, non-Latin scripts).
    c := upper(substring(w from 1 for 1));
    c := translate(
      c,
      'ÀÁÂÃÄÅĀĂĄÇĆČĐÈÉÊËĒĖĘÌÍÎÏĪÌÑŃÒÓÔÕÖØŌÙÚÛÜŪŸÝŻŹŠŞŚ',
      'AAAAAAAAACCCDEEEEEEEIIIIIIINOOOOOOOUUUUUYYZZSSS'
    );
    IF c ~ '^[A-Z]$' THEN
      out := out || c;
    END IF;
  END LOOP;
  -- Fall back to 'S' (school) if the name has zero A-Z initials —
  -- vanishingly rare, but better than producing empty IDs.
  IF length(out) = 0 THEN out := 'S'; END IF;
  RETURN out;
END;
$$;


-- Generate the next member_id for a school. Locks the schools row so
-- two concurrent inserts can't pick the same sequence number; the
-- UNIQUE index on (school_id, member_id) is the safety net if a
-- caller bypasses this function.
CREATE OR REPLACE FUNCTION public.generate_member_id(p_school_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  s_name   TEXT;
  prefix   TEXT;
  max_seq  INT;
BEGIN
  SELECT name INTO s_name
  FROM public.schools
  WHERE id = p_school_id
  FOR UPDATE;                            -- serialises generation per school
  IF s_name IS NULL THEN
    RAISE EXCEPTION 'Unknown school % when generating member_id', p_school_id;
  END IF;

  prefix := public.compute_school_prefix(s_name);

  -- Largest sequence already issued under this prefix at this school.
  SELECT COALESCE(MAX(CAST(substring(member_id FROM length(prefix) + 1) AS INT)), 0)
    INTO max_seq
  FROM public.profiles
  WHERE school_id = p_school_id
    AND member_id ~ ('^' || prefix || '[0-9]{6}$');

  RETURN prefix || lpad((max_seq + 1)::TEXT, 6, '0');
END;
$$;


-- BEFORE INSERT trigger that fills in member_id when the caller didn't
-- supply one. Skips parents + platform_admin per the spec.
CREATE OR REPLACE FUNCTION public.set_profile_member_id()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.member_id IS NOT NULL AND length(NEW.member_id) > 0 THEN
    RETURN NEW;                          -- caller pinned a specific ID
  END IF;
  IF NEW.role IN ('student', 'teacher', 'school_admin', 'employee') THEN
    NEW.member_id := public.generate_member_id(NEW.school_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_set_member_id ON public.profiles;
CREATE TRIGGER trg_profiles_set_member_id
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_profile_member_id();


-- ─── Backfill existing rows ──────────────────────────────────────
-- Existing students / teachers / school admins / employees get IDs
-- now so the column never displays "—" for someone already enrolled.
-- Done in created_at order per school so the sequence is stable.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, school_id
      FROM public.profiles
     WHERE member_id IS NULL
       AND role IN ('student', 'teacher', 'school_admin', 'employee')
     ORDER BY school_id, created_at, id
  LOOP
    UPDATE public.profiles
       SET member_id = public.generate_member_id(r.school_id)
     WHERE id = r.id;
  END LOOP;
END $$;


-- ─── Update get_user_context() to surface member_id ──────────────
-- The signed-in user can see their own school-issued ID in the UI.
CREATE OR REPLACE FUNCTION public.get_user_context()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_profile RECORD;
BEGIN
  SELECT p.*, s.name as school_name, s.type as school_type, s.access_suspended
  INTO v_profile
  FROM public.profiles p
  JOIN public.schools s ON s.id = p.school_id
  WHERE p.user_id = auth.uid()
    AND p.is_active = TRUE
  LIMIT 1;

  IF v_profile IS NULL THEN
    RETURN json_build_object('error', 'No active profile found');
  END IF;

  IF v_profile.access_suspended = TRUE AND v_profile.role <> 'platform_admin' THEN
    RETURN json_build_object('error', 'School access suspended');
  END IF;

  RETURN json_build_object(
    'profile_id',  v_profile.id,
    'user_id',     v_profile.user_id,
    'school_id',   v_profile.school_id,
    'school_name', v_profile.school_name,
    'school_type', v_profile.school_type,
    'role',        v_profile.role,
    'first_name',  v_profile.first_name,
    'last_name',   v_profile.last_name,
    'email',       v_profile.email,
    'avatar_url',  v_profile.avatar_url,
    'member_id',   v_profile.member_id
  );
END;
$$;
