-- ═══════════════════════════════════════════════════════════════════
-- 029 · Institutional IDs — per-school, per-role, role-letter-tagged
-- ───────────────────────────────────────────────────────────────────
-- Supersedes the simpler `member_id` from migration 028. The school
-- owner asked for a different format:
--
--   institutional_id = [SCHOOL_PREFIX (2)][ROLE_LETTER (1)][6 DIGITS]
--
-- SCHOOL_PREFIX rules (always exactly 2 uppercase letters):
--   • Name has 2+ words → first letter of word 1 + first letter of
--     word 2.  "Akron Masjid" → "AM"
--   • Name is 1 word     → first two letters uppercased.
--                          "Sahel" → "SA",  "L" → "LX" (padded with X)
--
-- ROLE_LETTER:
--   teacher       → T
--   employee      → E
--   school_admin  → A
--   student       → S
--   (parent + platform_admin are NOT issued an institutional ID.)
--
-- 6-DIGIT SEQUENCE: zero-padded, sequential PER (school_id, role).
-- A teacher and a student at the same school both start from 000001.
--
-- Migration is SAFE / REVERSIBLE:
--   • adds a NEW column `institutional_id` alongside the existing
--     `member_id` — no overwrite, no FK breakage.
--   • backfill walks rows in (school, role, created_at) order so
--     sequences are deterministic on every re-run.
--   • unique constraint enforced at the DB level so two simultaneous
--     INSERTs that bypass the trigger cannot collide silently.
-- ═══════════════════════════════════════════════════════════════════


-- ─── Column ──────────────────────────────────────────────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS institutional_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_profiles_institutional_id_per_school
  ON public.profiles(school_id, institutional_id)
  WHERE institutional_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_institutional_id
  ON public.profiles(institutional_id) WHERE institutional_id IS NOT NULL;

COMMENT ON COLUMN public.profiles.institutional_id IS
  'Per-school per-role identifier, e.g. "AMT000123" (Akron Masjid, Teacher, #123).
   Generated by the trg_profiles_set_institutional_id trigger when a profile is
   inserted with no explicit value. The pure-TS mirror of this logic lives in
   src/lib/idGenerator/generate.ts — keep both in sync.';


-- ─── School prefix (always 2 chars) ──────────────────────────────
-- Pads "L" → "LX" so the prefix is always exactly two letters even
-- for one-character school names. Accented initials are translit-
-- erated, so "École" → "EC", "Université" → "UN".
CREATE OR REPLACE FUNCTION public.compute_school_prefix_v2(s_name TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  parts    TEXT[];
  out_text TEXT := '';
  word     TEXT;
  c1       TEXT;
  c2       TEXT;
  filtered TEXT[];
BEGIN
  parts := regexp_split_to_array(trim(coalesce(s_name, '')), '\s+');
  -- Drop empty tokens (consecutive spaces collapse).
  SELECT array_agg(p) INTO filtered FROM unnest(parts) p WHERE length(p) > 0;
  IF filtered IS NULL OR array_length(filtered, 1) = 0 THEN
    RETURN 'SX';
  END IF;

  IF array_length(filtered, 1) >= 2 THEN
    -- Two-word school: first letter of word 1 + first letter of word 2.
    c1 := upper(substring(filtered[1] from 1 for 1));
    c2 := upper(substring(filtered[2] from 1 for 1));
    out_text := c1 || c2;
  ELSE
    -- Single-word school: first two letters. Pad with X if too short.
    word := filtered[1];
    c1   := upper(substring(word from 1 for 1));
    c2   := CASE WHEN length(word) >= 2 THEN upper(substring(word from 2 for 1)) ELSE 'X' END;
    out_text := c1 || c2;
  END IF;

  -- Transliterate common accented forms back to ASCII A-Z.
  out_text := translate(
    out_text,
    'ÀÁÂÃÄÅĀĂĄÇĆČĐÈÉÊËĒĖĘÌÍÎÏĪÌÑŃÒÓÔÕÖØŌÙÚÛÜŪŸÝŻŹŠŞŚ',
    'AAAAAAAAACCCDEEEEEEEIIIIIIINOOOOOOOUUUUUYYZZSSS'
  );
  -- Replace anything outside A-Z with X so the format stays well-formed.
  out_text := regexp_replace(out_text, '[^A-Z]', 'X', 'g');
  -- Guarantee exactly 2 chars (defensive — should already be 2).
  RETURN substring(out_text || 'XX' from 1 for 2);
END;
$$;


-- ─── Role letter ─────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.role_letter(p_role TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE p_role
    WHEN 'teacher'      THEN 'T'
    WHEN 'employee'     THEN 'E'
    WHEN 'school_admin' THEN 'A'
    WHEN 'student'      THEN 'S'
    ELSE NULL          -- parent / platform_admin → no ID issued
  END;
$$;


-- ─── ID generator with per-(school, role) sequence ───────────────
-- Concurrency-safe: takes a row-level lock on the schools row before
-- looking up the max sequence, so two simultaneous registrations
-- always get sequential numbers.
CREATE OR REPLACE FUNCTION public.generate_institutional_id(
  p_school_id UUID,
  p_role      TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  s_name      TEXT;
  prefix      TEXT;
  rletter     TEXT;
  max_seq     INT;
  candidate   TEXT;
BEGIN
  rletter := public.role_letter(p_role);
  IF rletter IS NULL THEN
    RETURN NULL;
  END IF;

  -- Serialise per-school so concurrent inserts don't collide.
  SELECT name INTO s_name
    FROM public.schools
   WHERE id = p_school_id
   FOR UPDATE;
  IF s_name IS NULL THEN
    RAISE EXCEPTION 'Unknown school % when generating institutional_id', p_school_id;
  END IF;

  prefix := public.compute_school_prefix_v2(s_name);
  candidate := prefix || rletter;        -- e.g. "AMT"

  SELECT COALESCE(MAX(CAST(substring(institutional_id FROM length(candidate) + 1) AS INT)), 0)
    INTO max_seq
    FROM public.profiles
   WHERE school_id = p_school_id
     AND role = p_role
     AND institutional_id ~ ('^' || candidate || '[0-9]{6}$');

  RETURN candidate || lpad((max_seq + 1)::TEXT, 6, '0');
END;
$$;


-- ─── BEFORE INSERT trigger ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_profile_institutional_id()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.institutional_id IS NOT NULL AND length(NEW.institutional_id) > 0 THEN
    RETURN NEW;
  END IF;
  IF NEW.role IN ('student', 'teacher', 'school_admin', 'employee') THEN
    NEW.institutional_id := public.generate_institutional_id(NEW.school_id, NEW.role);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_set_institutional_id ON public.profiles;
CREATE TRIGGER trg_profiles_set_institutional_id
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_profile_institutional_id();


-- ─── Backfill existing rows ──────────────────────────────────────
-- Deterministic ordering: per (school, role) by created_at then id so
-- a re-run produces the same sequence numbers. Skips rows that already
-- have an ID (so the migration is idempotent).
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, school_id, role
      FROM public.profiles
     WHERE institutional_id IS NULL
       AND role IN ('student', 'teacher', 'school_admin', 'employee')
     ORDER BY school_id, role, created_at, id
  LOOP
    UPDATE public.profiles
       SET institutional_id = public.generate_institutional_id(r.school_id, r.role)
     WHERE id = r.id;
  END LOOP;
END $$;


-- ─── Update get_user_context() to surface institutional_id ──────
-- Replaces the projection from migration 028; keeps member_id in
-- the payload so any UI still reading it during the transition keeps
-- working until we remove it in a later migration.
CREATE OR REPLACE FUNCTION public.get_user_context()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_profile RECORD;
BEGIN
  SELECT p.*, s.name as school_name, s.type as school_type, s.access_suspended
    INTO v_profile
    FROM public.profiles p
    JOIN public.schools s ON s.id = p.school_id
   WHERE p.user_id = auth.uid()
     AND p.is_active = TRUE
   LIMIT 1;

  IF v_profile IS NULL THEN
    RETURN json_build_object('error', 'No active profile found');
  END IF;
  IF v_profile.access_suspended = TRUE AND v_profile.role <> 'platform_admin' THEN
    RETURN json_build_object('error', 'School access suspended');
  END IF;

  RETURN json_build_object(
    'profile_id',       v_profile.id,
    'user_id',          v_profile.user_id,
    'school_id',        v_profile.school_id,
    'school_name',      v_profile.school_name,
    'school_type',      v_profile.school_type,
    'role',             v_profile.role,
    'first_name',       v_profile.first_name,
    'last_name',        v_profile.last_name,
    'email',            v_profile.email,
    'avatar_url',       v_profile.avatar_url,
    'member_id',        v_profile.member_id,
    'institutional_id', v_profile.institutional_id
  );
END;
$$;
